site_name: Cuems Editor
repo_url: https://github.com/stagesoft/cuems-editor
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
